### ISSUE TITLE
check small mistake

### ISSUE THREAD

**Issue by souravdas142** [semimqmo/sekiro_grub_theme#2]
Hi, you did excellent Work. But there is one small typo/mistake https://github.com/semimqmo/sekiro_grub_theme/blob/a7047485ce7c7b07e70d5d64158322e9918e735c/Sekiro/theme.txt#L38 just change the line to `color = "#000000" `. I feel too lazy to give a PR. Please correct it.  Thanks

**Comment by semimqmo** [comment]
Thank you! I corrected it.
